import type { Metadata } from "next";
import { Geist, Geist_Mono , Ubuntu ,Ubuntu_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const UbuntuSans = Ubuntu({
  // variable: "--font-ubuntu-sans",
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "700",
});

const UbuntuMono = Ubuntu_Mono({
  // variable: "--font-ubuntu-mono",
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: "700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className={`${UbuntuSans.variable} ${UbuntuMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
